<?php

namespace Database\Seeders;

use App\Models\AnggotaKoperasi;
use Illuminate\Database\Seeder;

class AnggotaKoperasiSeed extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $anggota = [
            ['nama' => 'WIPI SUPRIYANTO, S.T., M.I.Kom.', 'nik' => '3302251106660002', 'bidang' => 'DIREKSI', 'nowa' => ''],
            ['nama' => 'RUDY SUTOMO, S.E.,M.Si.', 'nik' => '3302120903740001', 'bidang' => 'DIREKSI', 'nowa' => ''],
            ['nama' => 'WACHJONO, S.E.,Ak.,CA.', 'nik' => '3302241001710001', 'bidang' => 'SATUAN PENGAWAS INTERN', 'nowa' => ''],
            ['nama' => 'Dyah Retno Wulandari, S.Si.', 'nik' => '3303056804870003', 'bidang' => 'SATUAN PENGAWAS INTERN', 'nowa' => ''],
            ['nama' => 'Agustin Titik Ubayanti, S.E.', 'nik' => '3302256408700001', 'bidang' => 'SATUAN PENGAWAS INTERN', 'nowa' => ''],
            ['nama' => 'Yuliawaty, S.Sos.', 'nik' => '3302236107730005', 'bidang' => 'SATUAN PENGAWAS INTERN', 'nowa' => ''],
            ['nama' => 'Septin Rahayu, S.Kom.', 'nik' => '3303046509880002', 'bidang' => 'SATUAN PENGAWAS INTERN', 'nowa' => ''],
            ['nama' => 'Dodiet Widya Haryadi, S.E.', 'nik' => '3303151905800002', 'bidang' => 'SATUAN PENGAWAS INTERN', 'nowa' => ''],
            ['nama' => 'Suci Nur Hidayati, S.Si.', 'nik' => '3302196304880001', 'bidang' => 'SATUAN PENGAWAS INTERN', 'nowa' => ''],
            ['nama' => 'Purnomo Panji Basuki, S.T.', 'nik' => '3302272505750006', 'bidang' => 'BAG. PERENCANAAN & PENGEMBANGAN', 'nowa' => ''],
            ['nama' => 'Agus Riadi', 'nik' => '3302260512780003', 'bidang' => 'BAG. PERENCANAAN & PENGEMBANGAN', 'nowa' => ''],
            ['nama' => 'Dedi Setiawan', 'nik' => '3302271705750003', 'bidang' => 'BAG. PERENCANAAN & PENGEMBANGAN', 'nowa' => ''],
            ['nama' => 'Sudiro, S.T.', 'nik' => '3303030908830002', 'bidang' => 'BAG. PERENCANAAN & PENGEMBANGAN', 'nowa' => ''],
            ['nama' => 'Hidayati Purwaningrum, A.Md.', 'nik' => '3302046612850001', 'bidang' => 'BAG. PERENCANAAN & PENGEMBANGAN', 'nowa' => ''],
            ['nama' => 'Handy Sukma Pribadi, S.T.', 'nik' => '3302202809790001', 'bidang' => 'BAG. PERENCANAAN & PENGEMBANGAN', 'nowa' => ''],
            ['nama' => 'Firdaus Arif Rahman, S.T.', 'nik' => '3302250610890001', 'bidang' => 'BAG. PERENCANAAN & PENGEMBANGAN', 'nowa' => ''],
            ['nama' => 'AJI SETYO PRABOWO, S.Kom., M.M.', 'nik' => '3302261806920004', 'bidang' => 'BAG. PERENCANAAN & PENGEMBANGAN', 'nowa' => ''],
            ['nama' => 'Arif Maulana, S.T.', 'nik' => '3302231709930001', 'bidang' => 'BAG. PERENCANAAN & PENGEMBANGAN', 'nowa' => ''],
            ['nama' => 'Agus Purnomo', 'nik' => '3302252208830003', 'bidang' => 'BAG. PERENCANAAN & PENGEMBANGAN', 'nowa' => ''],
            ['nama' => 'Tito Amrulloh', 'nik' => '3302171612810001', 'bidang' => 'BAG. PERENCANAAN & PENGEMBANGAN', 'nowa' => ''],
            ['nama' => 'Doni Setiyawan', 'nik' => '3302211812800004', 'bidang' => 'BAG. PERENCANAAN & PENGEMBANGAN', 'nowa' => ''],
            ['nama' => 'SRI MARYATI, S.T.', 'nik' => '3302176603860002', 'bidang' => 'BAG. PERENCANAAN & PENGEMBANGAN', 'nowa' => ''],
            ['nama' => 'Andrian Kusuma Cahya', 'nik' => '3302241606930004', 'bidang' => 'BAG. PERENCANAAN & PENGEMBANGAN', 'nowa' => ''],
            ['nama' => 'Sigit Priyo Nugroho, S.T.', 'nik' => '3302223006760001', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ' 08112961127 '],
            ['nama' => 'Tri Joko Rismawanto, S.T.', 'nik' => '3302242310720003', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Bagas Anggoro Jenar, S.T.', 'nik' => '3301102003900001', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Teguh Setyanto', 'nik' => '3372042004870003', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Aji Hendriawan Kurnianto, S.Si.', 'nik' => '3302190809810002', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Adwie Aji Prabowo, S.H.', 'nik' => '3302240808860002', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Danang Wahyu Hajiyono', 'nik' => '3302110101910002', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'David Santoso', 'nik' => '3302251312890001', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Ian Willy Antono', 'nik' => '3302112907880003', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Abas Komara', 'nik' => '3302120108880003', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Imam Muzaki', 'nik' => '3302200501880001', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Januar Rusdianto', 'nik' => '3302190901830001', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Edy Purwanto, A.Md.Kom.', 'nik' => '3302100209900002', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Andi Priharyoko', 'nik' => '3302180104820001', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Iswoyo', 'nik' => '3302110506890002', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Ade Sulistiono', 'nik' => '3302111906880001', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'DIDIK NUR FATRIA, S.M.', 'nik' => '3302190911930002', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Okto Setiawan', 'nik' => '3302260510870001', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Nova Adiana', 'nik' => '3302221111910003', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Galih Rahmadhan', 'nik' => '3302050702970005', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Sugeng Riyadi', 'nik' => '3302212106850001', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Soegeng Setyadi, A.Md.', 'nik' => '3302262205760001', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Harry Kurniawan', 'nik' => '3302272506850001', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Hery Rujito', 'nik' => '3302111304800001', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Abdulah Lutfi Prabandaru', 'nik' => '3302200204970003', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Adi Priyo Setiawan', 'nik' => '3302261612890001', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Ginanjar Setiawan', 'nik' => '3302201201900001', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Damar Gilas Tirani', 'nik' => '', 'bidang' => '', 'nowa' => ''],
            ['nama' => 'Slamet Pujianto', 'nik' => '3302112303920001', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Sabrianto', 'nik' => '3302252710980001', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Guruh Adhy Pradana', 'nik' => '3304041008970005', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Utoro', 'nik' => '3302161610850001', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Gatot Sagiyono', 'nik' => '3302210111830002', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Ahsin Latif Muhamad Arham', 'nik' => '3302202404950003', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 1', 'nowa' => ''],
            ['nama' => 'Wachyu Harjoto, S.T.', 'nik' => '3302272609770002', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Gusmanto', 'nik' => '3302261808720005', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Darso', 'nik' => '3302271503720001', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Sugiarto', 'nik' => '3302261911850001', 'bidang' => 'CABANG AJIBARANG', 'nowa' => ''],
            ['nama' => 'Eko Amriyatno, A.Md.', 'nik' => '3302120910850003', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Adi Nugroho', 'nik' => '3302242904770004', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Ari Afandi', 'nik' => '3302123101850002', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Jiwan Santoso', 'nik' => '3311051409810001', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Fendi Irwansyah', 'nik' => '3302201104910002', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Sudiyono', 'nik' => '3302251110760001', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'MOCHAMMAD ISNAENI MAULANA, A.Md.', 'nik' => '3302260708810002', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Nurma Ery Budiyanto', 'nik' => '3302220706890002', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Eka Heriyanto', 'nik' => '3302222108830002', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Alta Yunade, S.Kom.', 'nik' => '3573032206850004', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Heri Kristika', 'nik' => '3302223010850001', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Aya Pratomo Sumitro', 'nik' => '', 'bidang' => '', 'nowa' => ''],
            ['nama' => 'Amin Suyitno', 'nik' => '3302210105830005', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Adi Wahyono', 'nik' => '3302182010930001', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Panji Gunawan', 'nik' => '3302020806960006', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Rofik Nurul Huda', 'nik' => '3302171605960001', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Narko', 'nik' => '3302141101930002', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Andi Kristanto', 'nik' => '3302270409810003', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Fredy Prasetyo', 'nik' => '3302241409840003', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Saein', 'nik' => '3302170103830003', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Pradhipta Nugraha Adhi, S.Hum.', 'nik' => '3273191707960003', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Wahyu Dwiyantoro', 'nik' => '3302161001950002', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Satrio Bagus Widyantoro', 'nik' => '3302162509000004', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Nantoro', 'nik' => '3302171312930003', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Imam Satrio, S.Pd.I.', 'nik' => '3302202304930002', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Adi Prayitno', 'nik' => '2201072803950004', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Lian Dwi Saputra', 'nik' => '330221050395', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Rosadiyantoro', 'nik' => '3173081106921001', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Aldi Maulana Restuaji', 'nik' => '3302251202030002', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Agus Trima Sutianto', 'nik' => '3302161408850006', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Fendri Hidayat', 'nik' => '3302131006930001', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Dwi Purwanto', 'nik' => '3302213011840005', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Toni Setiawan', 'nik' => '3302162907810001', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Bagus Panuntun, S.Psi.', 'nik' => '3302271704960002', 'bidang' => 'BAG. PRODUKSI & DISTRIBUSI 2', 'nowa' => ''],
            ['nama' => 'Yustyarso, S.T.', 'nik' => '3503121005780001', 'bidang' => 'BAG. PENGENDALIAN TEKNIK', 'nowa' => ''],
            ['nama' => 'MASRUROH, S.Si', 'nik' => '3302176508790001', 'bidang' => 'BAG. PENGENDALIAN TEKNIK', 'nowa' => ''],
            ['nama' => 'Khanafi Yusuf, S.T.', 'nik' => '3302202708900001', 'bidang' => 'BAG. PENGENDALIAN TEKNIK', 'nowa' => ''],
            ['nama' => 'Burhanuddin Ahmad, A.Md.', 'nik' => '3302240611770005', 'bidang' => 'BAG. PENGENDALIAN TEKNIK', 'nowa' => ''],
            ['nama' => 'ARI BANGKIT SUSANTO, S.Si.', 'nik' => '3302122005790001', 'bidang' => 'BAG. PENGENDALIAN TEKNIK', 'nowa' => ''],
            ['nama' => 'Krisna Muliawati, S.Pi.', 'nik' => '3302216803820002', 'bidang' => 'BAG. PENGENDALIAN TEKNIK', 'nowa' => ''],
            ['nama' => 'Toni Ardianto Wibowo', 'nik' => '3302223103870001', 'bidang' => 'BAG. PENGENDALIAN TEKNIK', 'nowa' => ''],
            ['nama' => 'Rochmat Mardi Waluyo', 'nik' => '3302241904830001', 'bidang' => 'BAG. PENGENDALIAN TEKNIK', 'nowa' => ''],
            ['nama' => 'TRISNANDI YUDASTIRA, S.M.', 'nik' => '3302200909840002', 'bidang' => 'BAG. PENGENDALIAN TEKNIK', 'nowa' => ''],
            ['nama' => 'Dedi Setiawan, S.T.', 'nik' => '3302183112850010', 'bidang' => 'BAG. PENGENDALIAN TEKNIK', 'nowa' => ''],
            ['nama' => 'Adi Saputra, A.Md.', 'nik' => '3302272604850003', 'bidang' => 'BAG. PENGENDALIAN TEKNIK', 'nowa' => ''],
            ['nama' => 'Teguh Ahmari, S.T.', 'nik' => '3302110206820003', 'bidang' => 'BAG. PENGENDALIAN TEKNIK', 'nowa' => ''],
            ['nama' => 'Imam Priyono', 'nik' => '3302102108840001', 'bidang' => 'BAG. PENGENDALIAN TEKNIK', 'nowa' => ''],
            ['nama' => 'Amin Riyadi, A.Md.', 'nik' => '3302161406790006', 'bidang' => 'BAG. PENGENDALIAN TEKNIK', 'nowa' => ''],
            ['nama' => 'Sugiat, A.Md.', 'nik' => '3302122310780001', 'bidang' => 'BAG. PENGENDALIAN TEKNIK', 'nowa' => ''],
            ['nama' => 'Kasiyanto', 'nik' => '3302220506880001', 'bidang' => 'BAG. PENGENDALIAN TEKNIK', 'nowa' => ''],
            ['nama' => 'Diah Winarni, S.H.', 'nik' => '3302265611820002', 'bidang' => 'BAG. PENGENDALIAN TEKNIK', 'nowa' => ''],
            ['nama' => 'Cahyadi Waskito, S.E.', 'nik' => '3302220312760002', 'bidang' => 'BAG. KESEKRETARIATAN', 'nowa' => ''],
            ['nama' => 'Maya Prasetyowati, S.E.', 'nik' => '3302226005800003', 'bidang' => 'BAG. KESEKRETARIATAN', 'nowa' => ''],
            ['nama' => 'Toro, S.H.', 'nik' => '3302221806800003', 'bidang' => 'BAG. KESEKRETARIATAN', 'nowa' => ''],
            ['nama' => 'Yuni Tri Rahmawati, S.E.', 'nik' => '3302225204730002', 'bidang' => 'BAG. KESEKRETARIATAN', 'nowa' => ''],
            ['nama' => 'Citra Anggraeni, S.TP.', 'nik' => '3302246303840005', 'bidang' => 'BAG. KESEKRETARIATAN', 'nowa' => ''],
            ['nama' => 'Januar Dwi Hendrawan, S.T.', 'nik' => '3302212101860003', 'bidang' => 'BAG. KESEKRETARIATAN', 'nowa' => ''],
            ['nama' => 'Feza Putri Rizqika', 'nik' => '', 'bidang' => '', 'nowa' => ''],
            ['nama' => 'Martono, S.H.', 'nik' => '3302221903750002', 'bidang' => 'BAG. KESEKRETARIATAN', 'nowa' => ''],
            ['nama' => 'Lutfi Nurhidayat', 'nik' => '3302182011930005', 'bidang' => 'BAG. KESEKRETARIATAN', 'nowa' => ''],
            ['nama' => 'Nawal Ika Nur Fathin', 'nik' => '3302275410990001', 'bidang' => 'BAG. KESEKRETARIATAN', 'nowa' => ''],
            ['nama' => 'Wahyu Hidayat', 'nik' => '3302222012920001', 'bidang' => 'BAG. KESEKRETARIATAN', 'nowa' => ''],
            ['nama' => 'TIARA DWIHANASETYA, S.H., M.H.', 'nik' => '3302274404940001', 'bidang' => 'BAG. KESEKRETARIATAN', 'nowa' => ''],
            ['nama' => 'KHARIS SURYANDARU PRATAMA, S.Kom., M.Cs.', 'nik' => '3302221805940001', 'bidang' => 'BAG. KESEKRETARIATAN', 'nowa' => ''],
            ['nama' => 'Endi Setyo Pribadi, S.H.', 'nik' => '3302212012880005', 'bidang' => 'BAG. KESEKRETARIATAN', 'nowa' => ''],
            ['nama' => 'Syarif Chandra Wijaya, S.IP.', 'nik' => '3302261212920001', 'bidang' => 'BAG. KESEKRETARIATAN', 'nowa' => ''],
            ['nama' => 'Rifani Kusumawardani, S.E.', 'nik' => '2171106305849006', 'bidang' => 'BAG. KESEKRETARIATAN', 'nowa' => ''],
            ['nama' => 'Nur Komariyah, S.E.', 'nik' => '3302256204750001', 'bidang' => 'BAG. KEUANGAN', 'nowa' => ''],
            ['nama' => 'MARLINA PRATIWI, S.Kom', 'nik' => '3302264608860001', 'bidang' => 'BAG. KEUANGAN', 'nowa' => ''],
            ['nama' => 'Amalia Fitriani, S.Ak.', 'nik' => '3328106807860001', 'bidang' => 'BAG. KEUANGAN', 'nowa' => ''],
            ['nama' => 'Rizki Yuliarto Rajasa, S.E.', 'nik' => '3302242307830002', 'bidang' => 'BAG. KEUANGAN', 'nowa' => ''],
            ['nama' => 'Wahyu Maulidia Prihartini', 'nik' => '3302165406000002', 'bidang' => 'BAG. KEUANGAN', 'nowa' => ''],
            ['nama' => 'Widodo Tri Agus Arisandi', 'nik' => '3302212608890004', 'bidang' => 'BAG. KEUANGAN', 'nowa' => ''],
            ['nama' => 'Satrio Aji Pamungkas', 'nik' => '3302251303010001', 'bidang' => 'BAG. KEUANGAN', 'nowa' => ''],
            ['nama' => 'Erna Budiarti, S.E.', 'nik' => '3302184603920001', 'bidang' => 'BAG. KEUANGAN', 'nowa' => ''],
            ['nama' => 'Herdiasih Tris Windarti, A.Md.', 'nik' => '3302206909720003', 'bidang' => 'BAG. SUMBER DAYA MANUSIA & TI', 'nowa' => ''],
            ['nama' => 'Untung Waluyo, S.Kom.', 'nik' => '3302240403760002', 'bidang' => 'BAG. SUMBER DAYA MANUSIA & TI', 'nowa' => ''],
            ['nama' => 'Lisa Rosmawati, S.Ak.', 'nik' => '3302275502790001', 'bidang' => 'BAG. SUMBER DAYA MANUSIA & TI', 'nowa' => ''],
            ['nama' => 'ABDUL AZIZ MIFTAHUDDIN, S.Kom.', 'nik' => '3302201803890004', 'bidang' => 'BAG. SUMBER DAYA MANUSIA & TI', 'nowa' => ''],
            ['nama' => 'Eka Setyaningsih, S.E.', 'nik' => '3302096506860001', 'bidang' => 'BAG. SUMBER DAYA MANUSIA & TI', 'nowa' => ''],
            ['nama' => 'Eka Era Sri Pristiyani', 'nik' => '3302264210880001', 'bidang' => 'BAG. SUMBER DAYA MANUSIA & TI', 'nowa' => ''],
            ['nama' => 'ERVITA SEPTIA Y., S.KM.', 'nik' => '3301076409900001', 'bidang' => 'BAG. SUMBER DAYA MANUSIA & TI', 'nowa' => ''],
            ['nama' => 'DIAH MAESAROH, S.E.', 'nik' => '3302195105930002', 'bidang' => 'BAG. SUMBER DAYA MANUSIA & TI', 'nowa' => ''],
            ['nama' => 'Widhy Roesyani Indrawati, S.H.', 'nik' => '3302275308700002', 'bidang' => 'BAG. SUMBER DAYA MANUSIA & TI', 'nowa' => ''],
            ['nama' => 'Muhammad Amran Perdani', 'nik' => '3302201710870002', 'bidang' => 'BAG. SUMBER DAYA MANUSIA & TI', 'nowa' => ''],
            ['nama' => 'Tintus Tri Wibowo, S.Kom.', 'nik' => '3302262808900001', 'bidang' => 'BAG. SUMBER DAYA MANUSIA & TI', 'nowa' => ''],
            ['nama' => 'Bagus Sudrajat, S.Kom.', 'nik' => '3302100808900001', 'bidang' => 'BAG. SUMBER DAYA MANUSIA & TI', 'nowa' => ''],
            ['nama' => 'Oka Sigit, S.Kom.', 'nik' => '3302272910910001', 'bidang' => 'BAG. SUMBER DAYA MANUSIA & TI', 'nowa' => ''],
            ['nama' => 'GAYUH EKA KUMALA, S.Mat.', 'nik' => '3302254508950001', 'bidang' => 'BAG. SUMBER DAYA MANUSIA & TI', 'nowa' => ''],
            ['nama' => 'Untung Wahyuningrat, S.H.', 'nik' => '3302121805710003', 'bidang' => 'BAG. PERLENGKAPAN', 'nowa' => ''],
            ['nama' => 'Budi Supono', 'nik' => '3302200904730001', 'bidang' => 'BAG. PERLENGKAPAN', 'nowa' => ''],
            ['nama' => 'Leli Budi Hartono, S.E.', 'nik' => '3302231809760001', 'bidang' => 'BAG. PERLENGKAPAN', 'nowa' => ''],
            ['nama' => 'Edi Wahyono, S.E.', 'nik' => '3302190807730002', 'bidang' => 'BAG. PERLENGKAPAN', 'nowa' => ''],
            ['nama' => 'Hartono, A.Md.', 'nik' => '3303153001800001', 'bidang' => 'BAG. PERLENGKAPAN', 'nowa' => ''],
            ['nama' => 'Dwi Ari Wahyuni, S.E.', 'nik' => '3302255606860005', 'bidang' => 'BAG. PERLENGKAPAN', 'nowa' => ''],
            ['nama' => 'Yunan Wisnu Wardhana, S.T.', 'nik' => '3302261804930002', 'bidang' => 'BAG. PERLENGKAPAN', 'nowa' => ''],
            ['nama' => 'Bakhtiar Nur Cahyadi', 'nik' => '3302220309760001', 'bidang' => 'BAG. PERLENGKAPAN', 'nowa' => ''],
            ['nama' => 'Irfan Khumaeni', 'nik' => '3302182203790001', 'bidang' => 'BAG. PERLENGKAPAN', 'nowa' => ''],
            ['nama' => 'Elga Anastasia Clara, A.Md.', 'nik' => '3302276103920001', 'bidang' => 'BAG. PERLENGKAPAN', 'nowa' => ''],
            ['nama' => 'Sofyan Yaumal Badawi, S.Kom.', 'nik' => '3302250909940001', 'bidang' => 'BAG. PERLENGKAPAN', 'nowa' => ''],
            ['nama' => 'Wahyu Didik Setiawan', 'nik' => '3303142209790002', 'bidang' => 'BAG. PERLENGKAPAN', 'nowa' => ''],
            ['nama' => 'Siti Rahayu, S.T.', 'nik' => '3307066107840002', 'bidang' => 'CABANG PURWOKERTO 1', 'nowa' => ''],
            ['nama' => 'Subejo, S.E.', 'nik' => '3302190206760001', 'bidang' => 'CABANG PURWOKERTO 1', 'nowa' => ''],
            ['nama' => 'TRI AGUSTINAH, S.E.', 'nik' => '3302275708740001', 'bidang' => 'CABANG PURWOKERTO 1', 'nowa' => ''],
            ['nama' => 'Fenty Grace Mawaty, S.E.', 'nik' => '3302256405770001', 'bidang' => 'CABANG PURWOKERTO 1', 'nowa' => ''],
            ['nama' => 'Dadang Andrianto, A.Md.', 'nik' => '3302210608850002', 'bidang' => 'CABANG PURWOKERTO 1', 'nowa' => ''],
            ['nama' => 'Tulus Sejati', 'nik' => '3302121403860001', 'bidang' => 'CABANG PURWOKERTO 1', 'nowa' => ''],
            ['nama' => 'Dani Andiyanto, A.Md.', 'nik' => '3302120612820001', 'bidang' => 'CABANG PURWOKERTO 1', 'nowa' => ''],
            ['nama' => 'Soma Kumala, A.Md.', 'nik' => '3302220204840003', 'bidang' => 'CABANG PURWOKERTO 1', 'nowa' => ''],
            ['nama' => 'Warsono', 'nik' => '3302211502800004', 'bidang' => 'CABANG PURWOKERTO 1', 'nowa' => ''],
            ['nama' => 'Agus Triyadi, S.Sos.', 'nik' => '3302270108810004', 'bidang' => 'CABANG PURWOKERTO 1', 'nowa' => ''],
            ['nama' => 'Adhi Prasetyo', 'nik' => '3302271210770008', 'bidang' => 'CABANG PURWOKERTO 1', 'nowa' => ''],
            ['nama' => 'Setiyo Mutohar', 'nik' => '3302240410940006', 'bidang' => 'CABANG PURWOKERTO 1', 'nowa' => ''],
            ['nama' => 'Tri Yulianto', 'nik' => '3302120602830004', 'bidang' => 'CABANG PURWOKERTO 1', 'nowa' => ''],
            ['nama' => 'Eko Pujianto', 'nik' => '3302221604750002', 'bidang' => 'CABANG PURWOKERTO 1', 'nowa' => ''],
            ['nama' => 'Qifani Elyantoro', 'nik' => '3302270110760001', 'bidang' => 'CABANG PURWOKERTO 1', 'nowa' => ''],
            ['nama' => 'Ikhwan Susanto', 'nik' => '3302270203990002', 'bidang' => 'CABANG PURWOKERTO 1', 'nowa' => ''],
            ['nama' => 'Bayu Dwi Santoso', 'nik' => '3302272502970004', 'bidang' => 'CABANG PURWOKERTO 1', 'nowa' => ''],
            ['nama' => 'Imron Nur Rohman', 'nik' => '', 'bidang' => '', 'nowa' => ''],
            ['nama' => 'Andy Tri Marsetyo P.', 'nik' => '3302261703820001', 'bidang' => 'CABANG PURWOKERTO 1', 'nowa' => ''],
            ['nama' => 'Riza Fitriatna', 'nik' => '3302121812010004', 'bidang' => 'CABANG PURWOKERTO 1', 'nowa' => ''],
            ['nama' => 'YOGI DARMAWAN, S.M.', 'nik' => '3302270105970002', 'bidang' => 'CABANG PURWOKERTO 1', 'nowa' => ''],
            ['nama' => 'Nabila Oktafiana', 'nik' => '3302275810960002', 'bidang' => 'CABANG PURWOKERTO 1', 'nowa' => ''],
            ['nama' => 'WAHYU SEPTI C., S.M.', 'nik' => '3302275509820004', 'bidang' => 'CABANG PURWOKERTO 1', 'nowa' => ''],
            ['nama' => 'SETYA WATI, A.Md.', 'nik' => '3302255809850001', 'bidang' => 'CABANG PURWOKERTO 1', 'nowa' => ''],
            ['nama' => 'Alfreda Setyo Nugrahanto, S.E.', 'nik' => '3302270806910002', 'bidang' => 'CABANG PURWOKERTO 1', 'nowa' => ''],
            ['nama' => 'Wiwit Haryono', 'nik' => '3302212105830005', 'bidang' => 'CABANG PURWOKERTO 1', 'nowa' => ''],
            ['nama' => 'Agus Riadi, S.T.', 'nik' => '3302250409780001', 'bidang' => 'CABANG PURWOKERTO 2', 'nowa' => ''],
            ['nama' => 'Rudito Aji', 'nik' => '', 'bidang' => '', 'nowa' => ''],
            ['nama' => 'ELI AGUS SK, S.E.', 'nik' => '3302124108730002', 'bidang' => 'CABANG PURWOKERTO 2', 'nowa' => ''],
            ['nama' => 'Hany Haryati, S.H.', 'nik' => '3302226501710001', 'bidang' => 'CABANG PURWOKERTO 2', 'nowa' => ''],
            ['nama' => 'Bungkus Kris Basuki', 'nik' => '3302271608700003', 'bidang' => 'CABANG PURWOKERTO 2', 'nowa' => ''],
            ['nama' => 'NAWANG YUWONO, S.E.', 'nik' => '3302272609740001', 'bidang' => 'CABANG PURWOKERTO 2', 'nowa' => ''],
            ['nama' => 'MANAN RUKYAT', 'nik' => '3302272202800004', 'bidang' => 'CABANG PURWOKERTO 2', 'nowa' => ''],
            ['nama' => 'Kamso Imam Soghiron', 'nik' => '3302213005720002', 'bidang' => 'CABANG PURWOKERTO 2', 'nowa' => ''],
            ['nama' => 'Amin Surohman', 'nik' => '3302261810820003', 'bidang' => 'CABANG PURWOKERTO 2', 'nowa' => ''],
            ['nama' => 'Doni Supriharso', 'nik' => '3302180702860002', 'bidang' => 'CABANG PURWOKERTO 2', 'nowa' => ''],
            ['nama' => 'Nur Saefudin', 'nik' => '3302201501830004', 'bidang' => 'CABANG PURWOKERTO 2', 'nowa' => ''],
            ['nama' => 'Dhian Khoeron, S.E.', 'nik' => '3302271403900003', 'bidang' => 'CABANG PURWOKERTO 2', 'nowa' => ''],
            ['nama' => 'Harli', 'nik' => '3302210510790001', 'bidang' => 'CABANG PURWOKERTO 2', 'nowa' => ''],
            ['nama' => 'Sutarno', 'nik' => '3302181410760001', 'bidang' => 'CABANG PURWOKERTO 2', 'nowa' => ''],
            ['nama' => 'Arif Wibowo', 'nik' => '3302203012790002', 'bidang' => 'CABANG PURWOKERTO 2', 'nowa' => ''],
            ['nama' => 'Slamet Sugiarto', 'nik' => '3302260110780003', 'bidang' => 'CABANG PURWOKERTO 2', 'nowa' => ''],
            ['nama' => 'Yanuar Eko Priramdhana', 'nik' => '3302242301980002', 'bidang' => 'CABANG PURWOKERTO 2', 'nowa' => ''],
            ['nama' => 'ADITYA RAMADHAN NUGROHO', 'nik' => '3302220501980004', 'bidang' => 'CABANG PURWOKERTO 2', 'nowa' => ''],
            ['nama' => 'HIRDSA ROSETIAHERBOWO ADHI, S.E.', 'nik' => '3302251509910001', 'bidang' => 'CABANG PURWOKERTO 2', 'nowa' => ''],
            ['nama' => 'Warih Setiyawan', 'nik' => '3302262511800007', 'bidang' => 'CABANG PURWOKERTO 2', 'nowa' => ''],
            ['nama' => 'BEKTI NUGRAH TRIONO, A.Md.', 'nik' => '3302250802910001', 'bidang' => 'CABANG PURWOKERTO 2', 'nowa' => ''],
            ['nama' => 'Afi Aryati, S.H.', 'nik' => '3302167007800002', 'bidang' => 'CABANG PURWOKERTO 2', 'nowa' => ''],
            ['nama' => 'Bambang Kurniawan, S.E.', 'nik' => '3302261803770001', 'bidang' => 'CABANG PURWOKERTO 2', 'nowa' => ''],
            ['nama' => 'Mulyani', 'nik' => '3302276312790005', 'bidang' => 'CABANG PURWOKERTO 2', 'nowa' => ''],
            ['nama' => 'Mulyono, S.E.', 'nik' => '3302142804710002', 'bidang' => 'CABANG AJIBARANG', 'nowa' => '081327287040'],
            ['nama' => 'Nur Rochani Yasin, S.E.', 'nik' => '3302122208830001', 'bidang' => 'CABANG AJIBARANG', 'nowa' => ''],
            ['nama' => 'Heri Sugiartono, S.E.', 'nik' => '3302261209760001', 'bidang' => 'CABANG AJIBARANG', 'nowa' => '082134366854'],
            ['nama' => 'DEWI LUKITASARI, S.E.,Ak.,CA.', 'nik' => '3302276403800004', 'bidang' => 'CABANG AJIBARANG', 'nowa' => '081903511578'],
            ['nama' => 'Budi Priyanto', 'nik' => '3302022512740005', 'bidang' => 'CABANG AJIBARANG', 'nowa' => ''],
            ['nama' => 'Agus Sutrisno', 'nik' => '3302181708730001', 'bidang' => 'CABANG AJIBARANG', 'nowa' => ''],
            ['nama' => 'SUGIARTO', 'nik' => '3302261911850001', 'bidang' => 'CABANG AJIBARANG', 'nowa' => ''],
            ['nama' => 'Murdiyantono', 'nik' => '3302250705810003', 'bidang' => 'CABANG AJIBARANG', 'nowa' => ''],
            ['nama' => 'Tri Yudha Permadi', 'nik' => '3302250408900003', 'bidang' => 'CABANG AJIBARANG', 'nowa' => ''],
            ['nama' => 'Sidik Priyo Utomo', 'nik' => '', 'bidang' => '', 'nowa' => ''],
            ['nama' => 'Untung Widyanarko', 'nik' => '3302162611700001', 'bidang' => 'CABANG AJIBARANG', 'nowa' => ''],
            ['nama' => 'Subur Efendi', 'nik' => '3302141206820004', 'bidang' => 'CABANG AJIBARANG', 'nowa' => ''],
            ['nama' => 'Ikbal Tawakal', 'nik' => '3302141010850003', 'bidang' => 'CABANG AJIBARANG', 'nowa' => ''],
            ['nama' => 'Agus Yundriono', 'nik' => '3302260508780003', 'bidang' => 'CABANG AJIBARANG', 'nowa' => ''],
            ['nama' => 'Dwi Mulyono, S.Psi.', 'nik' => '3302271312810004', 'bidang' => 'CABANG AJIBARANG', 'nowa' => ''],
            ['nama' => 'Rendra Pristiadi', 'nik' => '3302170706780002', 'bidang' => 'CABANG AJIBARANG', 'nowa' => ''],
            ['nama' => 'Ika Widiyanti, S.E.', 'nik' => '3302244908830001', 'bidang' => 'CABANG AJIBARANG', 'nowa' => ''],
            ['nama' => 'Setiyani', 'nik' => '3302254810860001', 'bidang' => 'CABANG AJIBARANG', 'nowa' => ''],
            ['nama' => 'Cucu Soleha', 'nik' => '3302260602950001', 'bidang' => 'CABANG AJIBARANG', 'nowa' => ''],
            ['nama' => 'Ambang Setiawan', 'nik' => '3302132603720002', 'bidang' => 'CABANG WANGON', 'nowa' => ''],
            ['nama' => 'Wahyono, S.E.', 'nik' => '3302122007770002', 'bidang' => 'CABANG WANGON', 'nowa' => ''],
            ['nama' => 'Hendri Pramono, S.E.', 'nik' => '3301172501790001', 'bidang' => 'CABANG WANGON', 'nowa' => ' 085725705414 '],
            ['nama' => 'Aris Widyanto', 'nik' => '3302142411820001', 'bidang' => 'CABANG WANGON', 'nowa' => ''],
            ['nama' => 'Taufik Yudiono, S.H.', 'nik' => '3302030306810003', 'bidang' => 'CABANG WANGON', 'nowa' => ''],
            ['nama' => 'Ariefudin, S.T.', 'nik' => '3302141211870005', 'bidang' => 'CABANG WANGON', 'nowa' => ''],
            ['nama' => 'Wihan Setiaji, A.Md.', 'nik' => '3302040512790001', 'bidang' => 'CABANG WANGON', 'nowa' => ''],
            ['nama' => 'Vicky Onky Wicaksono', 'nik' => '', 'bidang' => '', 'nowa' => ''],
            ['nama' => 'Waluyo', 'nik' => '3301070804710003', 'bidang' => 'CABANG WANGON', 'nowa' => ''],
            ['nama' => 'Untung Waluyo', 'nik' => '3173051205811001', 'bidang' => 'CABANG WANGON', 'nowa' => ''],
            ['nama' => 'Sutono', 'nik' => '3671130504830008', 'bidang' => 'CABANG WANGON', 'nowa' => ''],
            ['nama' => 'Saiman', 'nik' => '3302021010830007', 'bidang' => 'CABANG WANGON', 'nowa' => ''],
            ['nama' => 'Agus Budiyono, S.E.', 'nik' => '3302031808750003', 'bidang' => 'CABANG WANGON', 'nowa' => ''],
            ['nama' => 'Sapto Adi Prabowo, S.T.', 'nik' => '', 'bidang' => '', 'nowa' => ''],
            ['nama' => 'Tri Agung Pamuji', 'nik' => '3302020808860001', 'bidang' => 'CABANG WANGON', 'nowa' => ''],
            ['nama' => 'Abdul Mukmin', 'nik' => '3302210802830001', 'bidang' => 'CABANG WANGON', 'nowa' => ''],
            ['nama' => 'Gani Kristian, A.Md.Kom.', 'nik' => '3302242512950002', 'bidang' => 'CABANG WANGON', 'nowa' => ''],
            ['nama' => 'Nur Iqbal Syakuro', 'nik' => '3302231001010001', 'bidang' => 'CABANG WANGON', 'nowa' => ''],
            ['nama' => 'Jeli Pramuhadianto, S.E.', 'nik' => '3302240607720002', 'bidang' => 'CABANG BANYUMAS', 'nowa' => ''],
            ['nama' => 'Endang Widoretno, S.E.', 'nik' => '3302236805740002', 'bidang' => 'CABANG BANYUMAS', 'nowa' => ''],
            ['nama' => 'Arief Pamuji Wibowo, S.E.', 'nik' => '3302221611720001', 'bidang' => 'CABANG BANYUMAS', 'nowa' => ''],
            ['nama' => 'Bambang Sugiatmoko', 'nik' => '3302191804700001', 'bidang' => 'CABANG BANYUMAS', 'nowa' => ''],
            ['nama' => 'Sukiman, S.E.', 'nik' => '3302021709730002', 'bidang' => 'CABANG BANYUMAS', 'nowa' => ''],
            ['nama' => 'Narotama Riowibowo', 'nik' => '3302200405870002', 'bidang' => 'CABANG BANYUMAS', 'nowa' => ''],
            ['nama' => 'Sabar Dwi Setyawan', 'nik' => '3302221407880002', 'bidang' => 'CABANG BANYUMAS', 'nowa' => ''],
            ['nama' => 'Sudarmanto', 'nik' => '3302112211800001', 'bidang' => 'CABANG BANYUMAS', 'nowa' => ''],
            ['nama' => 'Agus Triyono', 'nik' => '3303092603850001', 'bidang' => 'CABANG BANYUMAS', 'nowa' => ''],
            ['nama' => 'Andika Samba Wardani, S.M.', 'nik' => '3302202304910002', 'bidang' => 'CABANG BANYUMAS', 'nowa' => ''],
            ['nama' => 'Sufrendi', 'nik' => '3302101903870004', 'bidang' => 'CABANG BANYUMAS', 'nowa' => ''],
            ['nama' => 'Tri Yunianto', 'nik' => '3302201306800001', 'bidang' => 'CABANG BANYUMAS', 'nowa' => ''],
            ['nama' => 'Adiansah Ramadhan, S.Pd.', 'nik' => '3302090604890002', 'bidang' => 'CABANG BANYUMAS', 'nowa' => ''],
            ['nama' => 'Rujito', 'nik' => '3302110203830002', 'bidang' => 'CABANG BANYUMAS', 'nowa' => ''],
            ['nama' => 'Dwian Febrianto', 'nik' => '3302200202860003', 'bidang' => 'CABANG BANYUMAS', 'nowa' => ''],
            ['nama' => 'Sungad', 'nik' => '3302101005710003', 'bidang' => 'CABANG BANYUMAS', 'nowa' => ''],
            ['nama' => 'Ifan Suranto', 'nik' => '3302262607910001', 'bidang' => 'CABANG BANYUMAS', 'nowa' => ''],
            ['nama' => 'RAHAYU CHRISTIAN KUSUMA DEWI', 'nik' => '3302274511980002', 'bidang' => 'CABANG BANYUMAS', 'nowa' => ''],
            ['nama' => 'Dwi Nurhayati, S.Kom.', 'nik' => '3302116510870001', 'bidang' => 'CABANG BANYUMAS', 'nowa' => ''],
            ['nama' => 'Ratnasari Handayani, S.E.', 'nik' => '3303015111930003', 'bidang' => 'CABANG BANYUMAS', 'nowa' => ''],
            ['nama' => 'Dian Nur Asih, S.Kom.', 'nik' => '3302245912890001', 'bidang' => 'CABANG BANYUMAS', 'nowa' => ''],
            ['nama' => 'Yuke Martasari', 'nik' => '3302266807940005', 'bidang' => 'CABANG BANYUMAS', 'nowa' => ''],
            ['nama' => 'Warsito, S.T.', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '08161869667'],
            ['nama' => 'Fadjar Setiadi, S.E.', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Yoga Sugama, S.E.', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Suwitno', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Sirun', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Soberi', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Suwito', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Rahmadi', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Subagyo', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Suyitno', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Eri Susanto', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Edi Supriyanto', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Suparyono', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Sanjat Margani', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Suratno', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Lilit Fauzi', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Waryanto', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Dicky Anjar Rizkiyanto', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Sudiro', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Trimono', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Mugiono', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Darno', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Kuat Riyanto', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Andi Nur Robi', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '083866973587'],
            ['nama' => 'Tirkam', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Slamet A.', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Rasim', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Wanda Ai Barli', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '085727333583'],
            ['nama' => 'Eko Yulianto', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '082211560330'],
            ['nama' => 'Cahyanto', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '085727199959'],
            ['nama' => 'Agus Eko Susanto', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '081216184329'],
            ['nama' => 'Aris Setiono', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '085329123412'],
            ['nama' => 'Subuh Gangsar Prakoso', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '085869380383'],
            ['nama' => 'Tusy Herie Nurjanto Hadhi', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '083898787644'],
            ['nama' => 'Sarno Kristanto', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '081772884832'],
            ['nama' => 'Puji Suyanto', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Ade Sultomo', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Rois', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Nursino', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Kuswanto', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Yusuf Gunawan', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '085727179102'],
            ['nama' => 'Darkim', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Slamet B.', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Lukman Adhi Putra', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '081391658955'],
            ['nama' => 'Toni Medani', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Yoni Triyanto', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Witra Dwi Kuntoro', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '0895413827979'],
            ['nama' => 'Anggit Cahyo Purwanto', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '082220000302'],
            ['nama' => 'Saraswati Ayu Agustin', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Aziz Imanudin', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Adelia Margata', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '085329173852'],
            ['nama' => 'Esti Wulan Diarso', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Misbakhul Munir', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Agus Riyanto', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Yuli Atmaka', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Shentya Nurul Azizah', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Dian Safaroh', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Dendy Prasetyo Haryuwidikdo', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '085227882678'],
            ['nama' => 'Sofyan Masruri', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '088216443402'],
            ['nama' => 'Desnatan Arif Yudiyanto', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '085712042736'],
            ['nama' => 'Wahyu Putra Ramadan', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '083123429693'],
            ['nama' => 'Tarwo', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Arif Setiyadi', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => "Abiyyu Dhiya' Mahdy Atha", 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Rendra Agung Prabowo', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '085786276899'],
            ['nama' => 'Yosef Angga Tri Adi Nugraha', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '085848158150'],
            ['nama' => 'Ginanjar Gathot Priyono', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '082220235102'],
            ['nama' => 'Fajar Agus Sutriono', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '088229928839'],
            ['nama' => 'Afif Aziz', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Yusti Kevin Margastya', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Ilham Wangsa Sanjaya', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Billy Fadli Kusumo Dewo', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Rabani', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Siswanto', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Riyanto', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Yoga Tri Jatmiko', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Dimas Cahya Saputra', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Herjanu Reppymeta', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Dimas Rizqianto', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Amir Kristiawan', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Marruna Excel Pradana', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Hilman Nafinga', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Taufik Arifin', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Farach Ayu Andini', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '0882003212325'],
            ['nama' => 'Marko Aldo Tanasugarn', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '085174463435'],
            ['nama' => 'Ibnu Saputra', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '089527369903'],
            ['nama' => 'Azmi Tri Anggoro', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '085729820572'],
            ['nama' => 'Firmannulloh Dwi Purwoko', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '089682608222'],
            ['nama' => 'Saeful Anwar', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '085865771714'],
            ['nama' => 'Hesdin Rudinar Ramadhanti', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Prasetyo', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '082225715636'],
            ['nama' => 'Sugeng', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Suryanto', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Khoerul Fuadi', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Fadlan Nur Hidayat', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Anis Fuadi Al Mahbub', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '085643326894'],
            ['nama' => 'Fajar Ardiyanto', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Amalina Fajriyah', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '087716210600'],
            ['nama' => 'Fatharani Ghita Maisara', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Vivi Rahma N', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Fera Yulianti', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Yuni Tri Dina M', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Senjani Rahma Myralda', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Nungki Marshellina', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '088233479063'],
            ['nama' => 'Lisni Dite Novita Ansela', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '085600297960'],
            ['nama' => 'Tri Sulistiani', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '085866631748'],
            ['nama' => 'Setiani Prawati', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '082265106459'],
            ['nama' => 'Wikky Lifma Pangestu', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '089502392156'],
            ['nama' => 'Adyatma Caesar Maldini', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '085606785427'],
            ['nama' => 'Wiwit Junianto', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Muhammad Nurul Iman', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Muhammad Endra Allam A', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Reyndi Suryo Jatmiko', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Ivandra Dhiyaa Bagaskara', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '081326261110'],
            ['nama' => 'Gilang Riyoko', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Wasis Pambudi', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Ikhwan Hilmi Adani', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '085735764243'],
            ['nama' => 'Jihan Ragil Purwanto', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '085602522373'],
            ['nama' => 'Rizqi Dwi Pangestu', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '085842173077'],
            ['nama' => 'Teguh Pamungkas Hari S', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Nanda Prayoga', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Ariel Gagah Prastyo', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Alman Zaeni Prasetiyo', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Indra Widianto', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => ''],
            ['nama' => 'Pranasinta Fenindra', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '082135776480'],
            ['nama' => 'Fitria Putri Wibawani', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '081912236642'],
            ['nama' => 'Vinandito Nur Amri Prajamukti', 'nik' => '', 'bidang' => 'KARYAWAN KOPERASI', 'nowa' => '082314596671'],
            ['nama' => 'Sasi, SE.', 'nik' => '', 'bidang' => 'PENSIUNAN', 'nowa' => ' 081225791300 '],
            ['nama' => 'Sugiyanto', 'nik' => '', 'bidang' => 'PENSIUNAN', 'nowa' => ''],
            ['nama' => 'Setiyo Warsito, SH.', 'nik' => '', 'bidang' => 'PENSIUNAN', 'nowa' => ''],
            ['nama' => 'Setiawan, SH.', 'nik' => '', 'bidang' => 'PENSIUNAN', 'nowa' => ''],
            ['nama' => 'Charis Setiyabudi, SE.', 'nik' => '', 'bidang' => 'PENSIUNAN', 'nowa' => ''],
            ['nama' => 'Kuswondo', 'nik' => '', 'bidang' => 'PENSIUNAN', 'nowa' => ''],
            ['nama' => 'Kartika Dewi Widyani P., S.Pd.', 'nik' => '', 'bidang' => 'PENSIUNAN', 'nowa' => ''],
            ['nama' => 'Ir. Ach. Husein', 'nik' => '', 'bidang' => 'PENSIUNAN', 'nowa' => ''],
            ['nama' => 'Ir. Suwarsono', 'nik' => '', 'bidang' => 'PENSIUNAN', 'nowa' => ''],
            ['nama' => 'Bambang Parmono, SE.MBA.', 'nik' => '', 'bidang' => 'PENSIUNAN', 'nowa' => ''],
            ['nama' => 'Sarwono', 'nik' => '', 'bidang' => 'PENSIUNAN', 'nowa' => ''],
            ['nama' => 'Sukisno', 'nik' => '', 'bidang' => 'PENSIUNAN', 'nowa' => ''],
            ['nama' => 'Sutarman, SE.', 'nik' => '', 'bidang' => 'PENSIUNAN', 'nowa' => ''],
            ['nama' => 'Sutomo', 'nik' => '', 'bidang' => 'PENSIUNAN', 'nowa' => ''],
            ['nama' => 'Iman Riyanto', 'nik' => '', 'bidang' => 'PENSIUNAN', 'nowa' => ''],
            ['nama' => 'Muji Purnomo, SE.', 'nik' => '', 'bidang' => 'PENSIUNAN', 'nowa' => ''],
            ['nama' => 'Suyatno', 'nik' => '', 'bidang' => 'PENSIUNAN', 'nowa' => ''],
            ['nama' => 'Eko Priyono, ST.', 'nik' => '', 'bidang' => 'PENSIUNAN', 'nowa' => ''],
            ['nama' => 'Eko Purnomo', 'nik' => '', 'bidang' => 'PENSIUNAN', 'nowa' => ''],
        ];

        AnggotaKoperasi::query()->upsert(
            collect($anggota)
                ->map(fn (array $item) => [
                    'nama' => trim($item['nama']),
                    'nik' => trim($item['nik']),
                    'bidang' => trim($item['bidang']),
                    'nowa' => trim($item['nowa']),
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
                ->all(),
            ['nama', 'nik'],
            ['bidang', 'nowa', 'updated_at']
        );
    }
}
